all:
	g++ main.cpp -o res
	./res < tests/1.dat
	./res < tests/2.dat
	./res < tests/3.dat
	./res < tests/4.dat
	./res < tests/5.dat
	./res < tests/6.dat
	./res < tests/7.dat
	./res < tests/8.dat








